// <auto-generated />
using System;
using BlueCommand.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlueCommand.Infrastructure.Migrations
{
    [DbContext(typeof(BlueCommandDbContext))]
    partial class BlueCommandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlueCommand.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Actiune")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actiune");

                    b.Property<DateTime>("CreatLa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creat_la")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Detalii")
                        .HasColumnType("text")
                        .HasColumnName("detalii");

                    b.Property<string>("IpAdresa")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_adresa");

                    b.Property<int?>("UtilizatorId")
                        .HasColumnType("integer")
                        .HasColumnName("utilizator_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("UtilizatorId")
                        .HasDatabaseName("ix_audit_log_utilizator_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.DocumentDosar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaleFisier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cale_fisier");

                    b.Property<DateTime>("DataIncarcare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_incarcare")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DosarId")
                        .HasColumnType("integer")
                        .HasColumnName("dosar_id");

                    b.Property<int>("IncarcatDe")
                        .HasColumnType("integer")
                        .HasColumnName("incarcat_de");

                    b.Property<long?>("MarimeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("marime_bytes");

                    b.Property<string>("NumeFisier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nume_fisier");

                    b.HasKey("Id")
                        .HasName("pk_documente_dosar");

                    b.HasIndex("DosarId")
                        .HasDatabaseName("ix_documente_dosar_dosar_id");

                    b.HasIndex("IncarcatDe")
                        .HasDatabaseName("ix_documente_dosar_incarcat_de");

                    b.ToTable("documente_dosar", (string)null);
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.Dosar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualizatLa")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizat_la");

                    b.Property<int>("CreatDe")
                        .HasColumnType("integer")
                        .HasColumnName("creat_de");

                    b.Property<DateTime>("CreatLa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creat_la")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("DataIncident")
                        .HasColumnType("date")
                        .HasColumnName("data_incident");

                    b.Property<string>("Descriere")
                        .HasColumnType("text")
                        .HasColumnName("descriere");

                    b.Property<string>("NumarDosar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numar_dosar");

                    b.Property<int>("SectieId")
                        .HasColumnType("integer")
                        .HasColumnName("sectie_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("DESCHIS")
                        .HasColumnName("status");

                    b.Property<string>("TipIncident")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tip_incident");

                    b.Property<string>("Titlu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titlu");

                    b.HasKey("Id")
                        .HasName("pk_dosare");

                    b.HasIndex("CreatDe")
                        .HasDatabaseName("ix_dosare_creat_de");

                    b.HasIndex("NumarDosar")
                        .IsUnique()
                        .HasDatabaseName("ix_dosare_numar_dosar");

                    b.HasIndex("SectieId")
                        .HasDatabaseName("ix_dosare_sectie_id");

                    b.ToTable("dosare", (string)null);
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.DosarAgent", b =>
                {
                    b.Property<int>("DosarId")
                        .HasColumnType("integer")
                        .HasColumnName("dosar_id");

                    b.Property<int>("UtilizatorId")
                        .HasColumnType("integer")
                        .HasColumnName("utilizator_id");

                    b.HasKey("DosarId", "UtilizatorId")
                        .HasName("pk_dosar_agenti");

                    b.HasIndex("UtilizatorId")
                        .HasDatabaseName("ix_dosar_agenti_utilizator_id");

                    b.ToTable("dosar_agenti", (string)null);
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.IstoricDosar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CampModificat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("camp_modificat");

                    b.Property<int>("DosarId")
                        .HasColumnType("integer")
                        .HasColumnName("dosar_id");

                    b.Property<int>("ModificatDe")
                        .HasColumnType("integer")
                        .HasColumnName("modificat_de");

                    b.Property<DateTime>("ModificatLa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificat_la")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ValoareNoua")
                        .HasColumnType("text")
                        .HasColumnName("valoare_noua");

                    b.Property<string>("ValoareVeche")
                        .HasColumnType("text")
                        .HasColumnName("valoare_veche");

                    b.HasKey("Id")
                        .HasName("pk_istoric_dosare");

                    b.HasIndex("DosarId")
                        .HasDatabaseName("ix_istoric_dosare_dosar_id");

                    b.HasIndex("ModificatDe")
                        .HasDatabaseName("ix_istoric_dosare_modificat_de");

                    b.ToTable("istoric_dosare", (string)null);
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.IstoricSectie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CampModificat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("camp_modificat");

                    b.Property<int>("ModificatDe")
                        .HasColumnType("integer")
                        .HasColumnName("modificat_de");

                    b.Property<DateTime>("ModificatLa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificat_la")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("SectieId")
                        .HasColumnType("integer")
                        .HasColumnName("sectie_id");

                    b.Property<string>("ValoareNoua")
                        .HasColumnType("text")
                        .HasColumnName("valoare_noua");

                    b.Property<string>("ValoareVeche")
                        .HasColumnType("text")
                        .HasColumnName("valoare_veche");

                    b.HasKey("Id")
                        .HasName("pk_istoric_sectii");

                    b.HasIndex("ModificatDe")
                        .HasDatabaseName("ix_istoric_sectii_modificat_de");

                    b.HasIndex("SectieId")
                        .HasDatabaseName("ix_istoric_sectii_sectie_id");

                    b.ToTable("istoric_sectii", (string)null);
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.IstoricUtilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CampModificat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("camp_modificat");

                    b.Property<int>("ModificatDe")
                        .HasColumnType("integer")
                        .HasColumnName("modificat_de");

                    b.Property<DateTime>("ModificatLa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificat_la")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UtilizatorId")
                        .HasColumnType("integer")
                        .HasColumnName("utilizator_id");

                    b.Property<string>("ValoareNoua")
                        .HasColumnType("text")
                        .HasColumnName("valoare_noua");

                    b.Property<string>("ValoareVeche")
                        .HasColumnType("text")
                        .HasColumnName("valoare_veche");

                    b.HasKey("Id")
                        .HasName("pk_istoric_utilizatori");

                    b.HasIndex("ModificatDe")
                        .HasDatabaseName("ix_istoric_utilizatori_modificat_de");

                    b.HasIndex("UtilizatorId")
                        .HasDatabaseName("ix_istoric_utilizatori_utilizator_id");

                    b.ToTable("istoric_utilizatori", (string)null);
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.Raport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaleFisier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cale_fisier");

                    b.Property<DateTime>("DataGenerare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_generare")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FiltruPerioada")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("filtru_perioada");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tip");

                    b.Property<int>("UtilizatorId")
                        .HasColumnType("integer")
                        .HasColumnName("utilizator_id");

                    b.HasKey("Id")
                        .HasName("pk_rapoarte");

                    b.HasIndex("UtilizatorId")
                        .HasDatabaseName("ix_rapoarte_utilizator_id");

                    b.ToTable("rapoarte", (string)null);
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("denumire");

                    b.HasKey("Id")
                        .HasName("pk_roluri");

                    b.ToTable("roluri", (string)null);
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.Sectie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("adresa");

                    b.Property<DateTime>("CreatLa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creat_la")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double?>("Latitudine")
                        .HasColumnType("double precision")
                        .HasColumnName("latitudine");

                    b.Property<double?>("Longitudine")
                        .HasColumnType("double precision")
                        .HasColumnName("longitudine");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nume");

                    b.Property<string>("Zona")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zona");

                    b.HasKey("Id")
                        .HasName("pk_sectii");

                    b.ToTable("sectii", (string)null);
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_creare")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("EsteActiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("este_activ");

                    b.Property<string>("Grad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grad");

                    b.Property<string>("Nume")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nume");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("parola_hash");

                    b.Property<string>("Prenume")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenume");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<int?>("SectieId")
                        .HasColumnType("integer")
                        .HasColumnName("sectie_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_utilizatori");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_utilizatori_rol_id");

                    b.HasIndex("SectieId")
                        .HasDatabaseName("ix_utilizatori_sectie_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_utilizatori_username");

                    b.ToTable("utilizatori", (string)null);
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("BlueCommand.Domain.Entities.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_log_utilizator_utilizator_id");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.DocumentDosar", b =>
                {
                    b.HasOne("BlueCommand.Domain.Entities.Dosar", "Dosar")
                        .WithMany("Documente")
                        .HasForeignKey("DosarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documente_dosar_dosare_dosar_id");

                    b.HasOne("BlueCommand.Domain.Entities.Utilizator", "IncarcatDeUtilizator")
                        .WithMany("DocumenteIncarcate")
                        .HasForeignKey("IncarcatDe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documente_dosar_utilizatori_incarcat_de");

                    b.Navigation("Dosar");

                    b.Navigation("IncarcatDeUtilizator");
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.Dosar", b =>
                {
                    b.HasOne("BlueCommand.Domain.Entities.Utilizator", "CreatDeUtilizator")
                        .WithMany("DosareCreate")
                        .HasForeignKey("CreatDe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dosare_utilizatori_creat_de");

                    b.HasOne("BlueCommand.Domain.Entities.Sectie", "Sectie")
                        .WithMany("Dosare")
                        .HasForeignKey("SectieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dosare_sectii_sectie_id");

                    b.Navigation("CreatDeUtilizator");

                    b.Navigation("Sectie");
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.DosarAgent", b =>
                {
                    b.HasOne("BlueCommand.Domain.Entities.Dosar", "Dosar")
                        .WithMany("DosarAgenti")
                        .HasForeignKey("DosarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dosar_agenti_dosare_dosar_id");

                    b.HasOne("BlueCommand.Domain.Entities.Utilizator", "Utilizator")
                        .WithMany("DosarAgenti")
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dosar_agenti_utilizatori_utilizator_id");

                    b.Navigation("Dosar");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.IstoricDosar", b =>
                {
                    b.HasOne("BlueCommand.Domain.Entities.Dosar", "Dosar")
                        .WithMany("Istoric")
                        .HasForeignKey("DosarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_istoric_dosare_dosare_dosar_id");

                    b.HasOne("BlueCommand.Domain.Entities.Utilizator", "ModificatDeUtilizator")
                        .WithMany()
                        .HasForeignKey("ModificatDe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_istoric_dosare_utilizatori_modificat_de");

                    b.Navigation("Dosar");

                    b.Navigation("ModificatDeUtilizator");
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.IstoricSectie", b =>
                {
                    b.HasOne("BlueCommand.Domain.Entities.Utilizator", "ModificatDeUtilizator")
                        .WithMany()
                        .HasForeignKey("ModificatDe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_istoric_sectii_utilizatori_modificat_de");

                    b.HasOne("BlueCommand.Domain.Entities.Sectie", "Sectie")
                        .WithMany("Istoric")
                        .HasForeignKey("SectieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_istoric_sectii_sectii_sectie_id");

                    b.Navigation("ModificatDeUtilizator");

                    b.Navigation("Sectie");
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.IstoricUtilizator", b =>
                {
                    b.HasOne("BlueCommand.Domain.Entities.Utilizator", "ModificatDeUtilizator")
                        .WithMany()
                        .HasForeignKey("ModificatDe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_istoric_utilizatori_utilizatori_modificat_de");

                    b.HasOne("BlueCommand.Domain.Entities.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_istoric_utilizatori_utilizatori_utilizator_id");

                    b.Navigation("ModificatDeUtilizator");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.Raport", b =>
                {
                    b.HasOne("BlueCommand.Domain.Entities.Utilizator", "Utilizator")
                        .WithMany("Rapoarte")
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rapoarte_utilizatori_utilizator_id");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.Utilizator", b =>
                {
                    b.HasOne("BlueCommand.Domain.Entities.Rol", "Rol")
                        .WithMany("Utilizatori")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_utilizatori_roluri_rol_id");

                    b.HasOne("BlueCommand.Domain.Entities.Sectie", "Sectie")
                        .WithMany("Utilizatori")
                        .HasForeignKey("SectieId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_utilizatori_sectii_sectie_id");

                    b.Navigation("Rol");

                    b.Navigation("Sectie");
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.Dosar", b =>
                {
                    b.Navigation("Documente");

                    b.Navigation("DosarAgenti");

                    b.Navigation("Istoric");
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Utilizatori");
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.Sectie", b =>
                {
                    b.Navigation("Dosare");

                    b.Navigation("Istoric");

                    b.Navigation("Utilizatori");
                });

            modelBuilder.Entity("BlueCommand.Domain.Entities.Utilizator", b =>
                {
                    b.Navigation("DocumenteIncarcate");

                    b.Navigation("DosarAgenti");

                    b.Navigation("DosareCreate");

                    b.Navigation("Rapoarte");
                });
#pragma warning restore 612, 618
        }
    }
}
